apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: heptio-ark
  name: default
persistentVolumeProvider:
  name: aws
  config:
    region: eu-west-1
backupStorageProvider:
  name: aws
  bucket: <bucket>
  # Uncomment the below line to enable restic integration.
  # The format for resticLocation is <bucket>[/<prefix>],
  # e.g. "my-restic-bucket" or "my-restic-bucket/repos".
  # This MUST be a different bucket than the main Ark bucket
  # specified just above.
  # resticLocation: <YOUR_RESTIC_LOCATION>
  config:
    region: eu-west-1
backupSyncPeriod: 30m
gcSyncPeriod: 30m
scheduleSyncPeriod: 1m
restoreOnlyMode: false
