resource_types:
  - name: "github-status"                         
    type: "docker-image"                          
    source:                                       
      repository: "dpb587/github-status-resource" 
      tag: "master"                               
  - name: "slack-notification"
    type: "docker-image"
    source:
      repository: "cfcommunity/slack-notification-resource"
      tag: "latest"
resources:
  - name: "repo"
    type: "git"
    source:
      uri: git@github.com:ministryofjustice/cloudplatforms-pipeline-investigation.git
      branch: master
      private_key: ((the-private-key))
  - name: "repo-status"                                  
    type: "github-status"                                
    source:                                              
      repository: ministryofjustice/cloudplatforms-pipeline-investigation
      access_token: 075...
  - name: slack-alert
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/T02DYEB3A/B5DGDNYES/T3F...
jobs:
- name: say-hello-world-5
  plan:
  - get: "repo"
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["hello"]
    on_success:
      put: slack-alert
      params:
        text: "success"
    on_failure:
      put: slack-alert
      params:
        text: "failure"
  - put: "repo-status"
    params: { state: "success", commit: "repo" }
