image:
  repository: gcr.io/heptio-images/ark
  tag: v0.9.1
  pullPolicy: IfNotPresent

# A docker image with kubectl installed
kubectl:
  image:
    repository: claranet/gcloud-kubectl-docker
    tag: 1.0.0
    pullPolicy: IfNotPresent

# Only kube2iam: change the AWS_ACCOUNT_ID and HEPTIO_ARK_ROLE_NAME
podAnnotations: {}
#  iam.amazonaws.com/role: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<HEPTIO_ARK_ROLE_NAME>

rbac:
  create: true

resources: {}

serviceAccount:
  hook:
    create: true
    name:
  server:
    create: true
    name:

tolerations: []

nodeSelector: {}

## Parameters for the ' default' Config resource
## See https://heptio.github.io/ark/v0.9.0/config-definition
configuration:
  persistentVolumeProvider:
    name: aws
    config:
      region: eu-west-1

  backupStorageProvider:
    name: aws
    bucket: <bucket>
    config: {}
    #  region: eu-west-1
    #  s3ForcePathStyle:
    #  s3Url:
    #  kmsKeyId:

  backupSyncPeriod: 30m
  gcSyncPeriod: 30m
  scheduleSyncPeriod: 1m
  resourcePriorities: []
  restoreOnlyMode: false

credentials:
  existingSecret: cloud-credentials
  useSecret: true
  secretContents: {}